Repository see-the-glory/on-you-frontend, pull requests merged in 2022-11, with the labels that each got.

#65 피드생성, 댓글창, 댓글입력, 신고 임시완료
  api.ts
  navigation/HomeStack.tsx
  screens/Home.tsx
  screens/HomeRelevant/Accusation.tsx
  screens/HomeRelevant/AlarmPage.tsx
  screens/HomeRelevant/ImageSelecter.tsx
  screens/HomeRelevant/ModifiyPeed.tsx
  screens/HomeRelevant/MyClubSelector.tsx
  screens/HomeRelevant/ReplyPage.tsx
  types/feed.ts
Labels: 🤖 android, 📱 iOS

#71 모임 스케줄 달력 추가.
  android/build.gradle
  api.ts
  components/ClubList.tsx
  components/FloatingActionButton.tsx
  navigation/ClubStack.tsx
  package-lock.json
  package.json
  screens/Club/ClubHome.tsx
  screens/Club/ClubScheduleAdd.tsx
  screens/Club/ClubTopTabs.tsx
  screens/ClubCreation/ClubCreationStepThree.tsx
  screens/ClubCreation/ClubCreationSuccess.tsx
  screens/ClubManagement/ClubManagementMain.tsx
  screens/Clubs.tsx
  store/Reducers.js
  types/Club.ts
  yarn.lock
Labels: 🍗 enhancement

#76 모임 스케줄 등록
  .gitignore
  components/FloatingActionButton.tsx
  package-lock.json
  package.json
  screens/Club/ClubHome.tsx
  screens/Club/ClubScheduleAdd.tsx
  screens/Club/ClubScheduleAddModal.tsx
  yarn.lock
Labels: 🤖 android, 📱 iOS, 🎯 feature

#85 필터에 매칭되는 모임이 없을 경우 안내 문구 출력.
  screens/Clubs.tsx
Labels: 🎯 feature

#86 Modified ClubHome design, Delete expo-app-loading and Using expo-splash-screen & 누락된 홈 관련 라이브러리 추가 (규빈)
  App.js
  navigation/Tabs.tsx
  package-lock.json
  package.json
  screens/Club/ClubHome.tsx
  yarn.lock
Labels: 🍗 enhancement, 🛠 bugfix
