Repository see-the-glory/on-you-frontend, pull requests merged in 2022-08, with the labels that each got.

#25 재 업로드
  App.js
  navigation/HomeStack.tsx
  navigation/Root.tsx
  navigation/SearchStack.tsx
  navigation/Tabs.tsx
  package-lock.json
  package.json
  screens/Home.tsx
  screens/HomeRelevant/Accusation.tsx
  screens/HomeRelevant/AlarmPage.tsx
  screens/HomeRelevant/ImageSelecter.tsx
  screens/HomeRelevant/ModifiyPeed.tsx
  screens/HomeRelevant/ReplyPage.tsx
  screens/HomeRelevant/ReportComplete.tsx
  screens/Search.tsx
  screens/SearchPage/IntroduceGroup.tsx
  screens/SearchPage/Peed.tsx
  screens/SearchPage/PeedSelectPage.tsx
  screens/Temp.js
  screens/temp/Minxin.js
  screens/temp/config.js
  yarn.lock
Labels: 🤖 android, 📱 iOS, 🎯 feature

#27 220725 club home
  api.ts
  components/ClubHeader.tsx
  components/ClubList.tsx
  package.json
  screens/Club/ClubFeed.tsx
  screens/Club/ClubHome.tsx
  screens/Club/ClubScheduleAddModal.tsx
  screens/Club/ClubTopTabs.tsx
  screens/ClubCreation/ClubCreationFail.tsx
  screens/ClubCreation/ClubCreationStepThree.tsx
  screens/Clubs.tsx
  screens/Login/KakaoAuth.tsx
  types/club.ts
  yarn.lock
Labels: 🤖 android, 📱 iOS, 🎯 feature

#26 - 프로필 레이아웃 정렬
  api.ts
  ios/Podfile.lock
  package.json
  screens/Profile.tsx
  screens/Profile/EditProfile.tsx
  screens/Profile/MyClub.tsx
  yarn.lock
Labels: 🤖 android, 📱 iOS, 🎯 feature

#28 220804 refactoring
  .prettierrc
  App.js
  api.ts
  components/CircleIcon.tsx
  components/ClubHeader.tsx
  components/ClubList.tsx
  components/ClubTabBar.tsx
  components/FloatingActionButton.tsx
  components/HomeList.tsx
  navigation/ClubCreationStack.tsx
  navigation/HomeStack.tsx
  navigation/ProfileStack.tsx
  navigation/Root.tsx
  navigation/SearchStack.tsx
  navigation/Tabs.tsx
  package-lock.json
  package.json
  screens/Club/ClubFeed.tsx
  screens/Club/ClubHome.tsx
  screens/Club/ClubJoinModal.tsx
  screens/Club/ClubScheduleAddModal.tsx
  screens/Club/ClubScheduleModal.tsx
  screens/Club/ClubTopTabs.tsx
  screens/ClubCreation/ClubCreationFail.tsx
  screens/ClubCreation/ClubCreationStepOne.tsx
  screens/ClubCreation/ClubCreationStepThree.tsx
  screens/ClubCreation/ClubCreationStepTwo.tsx
  screens/ClubCreation/ClubCreationSuccess.tsx
  screens/Clubs.tsx
  screens/Home.tsx
  screens/HomeRelevant/Accusation.tsx
  screens/HomeRelevant/AlarmPage.tsx
  screens/HomeRelevant/CreateHomePeed.tsx
  screens/HomeRelevant/ImageSelecter.tsx
  screens/HomeRelevant/ModifiyPeed.tsx
  screens/HomeRelevant/ReplyPage.tsx
  screens/HomeRelevant/ReportComplete.tsx
  screens/Login/KakaoAuth.tsx
  screens/Profile.tsx
  screens/Profile/EditProfile.tsx
  screens/Search.tsx
  screens/SearchPage/IntroduceGroup.tsx
  screens/SearchPage/Peed.tsx
  screens/SearchPage/PeedSelectPage.tsx
  screens/Temp.js
  screens/temp/Minxin.js
  screens/temp/config.js
  types/club.ts
  yarn.lock
Labels: 🐛 bugbug, 🛠 bugfix

#38 220819 layout
  App.js
  api.ts
  assets/fonts/NotoSansKR-Bold.otf
  assets/fonts/NotoSansKR-Medium.otf
  assets/fonts/NotoSansKR-Regular.otf
  components/CircleIcon.tsx
  components/ClubHeader.tsx
  components/ClubList.tsx
  components/ClubTabBar.tsx
  components/CustomText.tsx
  components/CustomTextInput.tsx
  navigation/ClubCreationStack.tsx
  navigation/ClubManagementStack.tsx
  navigation/Tabs.tsx
  package-lock.json
  package.json
  screens/Club/ClubHome.tsx
  screens/Club/ClubJoinModal.tsx
  screens/Club/ClubScheduleAddModal.tsx
  screens/Club/ClubScheduleModal.tsx
  screens/Club/ClubTopTabs.tsx
  screens/ClubManagement/ClubEditBasics.tsx
  screens/ClubManagement/ClubEditIntroduction.tsx
  screens/ClubManagement/ClubEditMembers.tsx
  screens/ClubManagement/ClubManagementMain.tsx
  screens/Clubs.tsx
  store/reducers.js
  types/club.ts
  yarn.lock
Labels: 🐛 bugbug, 🛠 bugfix, 🎯 feature

#46 220825 clubs
  android/app/src/main/assets/index.android.bundle
  android/app/src/main/res/drawable-mdpi/assets_logo.png
  android/app/src/main/res/raw/assets_fonts_notosanskrbold.otf
  android/app/src/main/res/raw/assets_fonts_notosanskrmedium.otf
  android/app/src/main/res/raw/assets_fonts_notosanskrregular.otf
  api.ts
  components/CircleIcon.tsx
  components/ClubHeader.tsx
  components/ClubList.tsx
  components/CustomText.tsx
  package-lock.json
  package.json
  screens/Club/ClubHome.tsx
  screens/Club/ClubScheduleModal.tsx
  screens/ClubManagement/ClubEditBasics.tsx
  screens/ClubManagement/ClubEditIntroduction.tsx
  screens/ClubManagement/ClubEditMembers.tsx
  screens/ClubManagement/ClubManagementMain.tsx
  screens/Clubs.tsx
  screens/Home.tsx
  types/Club.ts
  yarn.lock
Labels: 🍗 enhancement, 🎯 feature
