Repository see-the-glory/on-you-frontend, pull requests merged in 2023-03, with the labels that each got.

#201 Fix axios setting to sign up
  App.js
  navigation/Root.tsx
  screens/Home.tsx
  screens/Login/JoinConfirm.tsx
  screens/Login/JoinStepEight.tsx
  screens/Profile.tsx
  screens/Profile/EditProfile.tsx
Labels: 🛠 bugfix, 🤖 android

#202 Add login api error exception routine
  navigation/Root.tsx
  screens/Login/JoinStepSuccess.tsx
  screens/Login/Login.tsx
Labels: 🛠 bugfix, 🤖 android

#203 230301_프로필 수정
  screens/Login/JoinStepOne.tsx
  screens/Profile.tsx
  screens/Profile/Account.tsx
  screens/Profile/Info.tsx
  screens/Profile/NotificationSetting.tsx
Labels: 🛠 bugfix, 🤖 android, 📱 iOS

#204 230301_회원가입
  assets/logo.png
  screens/Login/JoinConfirm.tsx
  screens/Login/JoinStepEight.tsx
  screens/Login/JoinStepFive.tsx
  screens/Login/JoinStepFour.tsx
  screens/Login/JoinStepOne.tsx
  screens/Login/JoinStepSeven.tsx
  screens/Login/JoinStepSix.tsx
  screens/Login/JoinStepSuccess.tsx
  screens/Login/JoinStepThree.tsx
  screens/Login/JoinStepTwo.tsx
Labels: 🛠 bugfix, 🤖 android, 📱 iOS

#205 Fix user info
  api.ts
  navigation/Root.tsx
  screens/Home.tsx
Labels: 🛠 bugfix, 🤖 android, 📱 iOS

#207 Fix logout bug
  navigation/Root.tsx
Labels: 🛠 bugfix, 🤖 android, 📱 iOS

#208 Fix feed refreshing after logout
  navigation/Root.tsx
Labels: 🛠 bugfix, 🤖 android, 📱 iOS

#209 Remove unused module import
  api.ts
  navigation/SignupStack.tsx
  screens/Club/ClubApplication.tsx
  screens/Club/ClubHome.tsx
  screens/Club/ClubJoin.tsx
  screens/Club/ClubScheduleEdit.tsx
  screens/Club/ClubScheduleModal.tsx
  screens/ClubCreation/ClubCreationStepThree.tsx
  screens/ClubCreation/ClubCreationSuccess.tsx
  screens/ClubManagement/ClubEditBasics.tsx
  screens/ClubManagement/ClubEditIntroduction.tsx
  screens/ClubManagement/ClubManagementMain.tsx
  screens/Clubs.tsx
  screens/Feed/ModifiyFeed.tsx
  screens/FeedCreation/ImageSelecter.tsx
  screens/FeedCreation/MyClubSelector.tsx
  screens/Home.tsx
  screens/Login/FindId.tsx
  screens/Login/FindIdResult.tsx
  screens/Login/FindLoginInfo.tsx
  screens/Login/FindPw.tsx
  screens/Login/FindPwResult.tsx
  screens/Login/Login.tsx
  screens/Profile.tsx
  screens/Profile/Account.tsx
  screens/Profile/BlockUserList.tsx
  screens/Profile/EditProfile.tsx
  screens/Profile/MyClub.tsx
  screens/Profile/Suggestion.tsx
Labels: 🍗 enhancement, 🤖 android, 📱 iOS

#210 Change club creation image module
  api.ts
  screens/Club/ClubTopTabs.tsx
  screens/ClubCreation/ClubCreationStepTwo.tsx
  screens/Clubs.tsx
Labels: 🛠 bugfix, 🤖 android, 📱 iOS

#211 Modify Area Modal Fix,
  screens/Feed/ModifiyFeed.tsx
  screens/FeedCreation/ImageSelecter.tsx
  screens/FeedCreation/MyClubSelector.tsx
Labels: 🛠 bugfix

#212 2023.03.04 BUG FIX
  screens/Club/ClubJoin.tsx
  screens/Club/ClubScheduleModal.tsx
  screens/Club/ClubTopTabs.tsx
  screens/ClubCreation/ClubCreationStepThree.tsx
  screens/ClubCreation/ClubCreationStepTwo.tsx
  screens/ClubCreation/ClubCreationSuccess.tsx
  screens/Profile/EditProfile.tsx
Labels: 🍗 enhancement, 🛠 bugfix, 🤖 android, 📱 iOS

#213 Fix club recruit default value, log in information button design
  screens/Club/ClubJoin.tsx
  screens/ClubManagement/ClubManagementMain.tsx
  screens/Login/FindLoginInfo.tsx
Labels: 🛠 bugfix, 🤖 android, 📱 iOS

#214 Add code push setting to iOS
  App.js
  ios/Podfile.lock
  ios/onyoufrontend.xcodeproj/project.pbxproj
  ios/onyoufrontend.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/onyoufrontend/AppDelegate.mm
  ios/onyoufrontend/Info.plist
  package-lock.json
  package.json
  yarn.lock
Labels: 📱 iOS, 🎯 feature

#215 Add android code push
  android/app/build.gradle
  android/app/src/main/java/com/onyoufrontend/MainApplication.java
  android/gradle.properties
  android/settings.gradle
Labels: 🤖 android, 🎯 feature

#216 Image drag Slide Fix
  babel.config.js
  package-lock.json
  package.json
  screens/FeedCreation/ImageSelecter.tsx
  yarn.lock
Labels: 🍗 enhancement, 🤖 android

#218 23.03.07 수정내역
  android/app/build.gradle
  android/gradle.properties
  api.ts
  components/FeedDetail.tsx
  navigation/Root.tsx
  navigation/SignupStack.tsx
  package-lock.json
  package.json
  screens/Clubs.tsx
  screens/SignUp/JoinStepEight.tsx
  screens/SignUp/JoinStepFive.tsx
  screens/SignUp/JoinStepFour.tsx
  screens/SignUp/JoinStepSeven.tsx
  screens/SignUp/JoinStepSix.tsx
  screens/SignUp/JoinStepSuccess.tsx
  screens/SignUp/JoinStepThree.tsx
  screens/SignUp/JoinStepTwo.tsx
Labels: 🍗 enhancement, 🤖 android, 📱 iOS

#219 ImageSelecter Area ImageDelete, Slider Fix
  screens/FeedCreation/ImageSelecter.tsx
Labels: 🛠 bugfix, 🤖 android

#217 23030_수정내역
  screens/Login/FindId.tsx
  screens/Login/FindLoginInfo.tsx
  screens/Login/FindPw.tsx
  screens/Login/Login.tsx
  screens/SignUp/JoinStepFour.tsx
  screens/SignUp/JoinStepSeven.tsx
  screens/SignUp/JoinStepSix.tsx
  screens/SignUp/JoinStepThree.tsx
  screens/SignUp/JoinStepTwo.tsx
Labels: 🛠 bugfix, 🤖 android, 📱 iOS

#220 Add Image Func Fix, myClub Refactoring
  screens/FeedCreation/ImageSelecter.tsx
  screens/FeedCreation/MyClubSelector.tsx
Labels: 🛠 bugfix, 🤖 android, 📱 iOS

#221 MyClub_Code Refactoring
  screens/FeedCreation/ImageSelecter.tsx
  screens/FeedCreation/MyClubSelector.tsx
Labels: 🍗 enhancement

#222 230307_수정내역
  screens/Profile/ChangePw.tsx
Labels: 🍗 enhancement

#223 Add duplcate check to sign up and club creation
  api.ts
  screens/ClubCreation/ClubCreationStepTwo.tsx
  screens/SignUp/JoinStepThree.tsx
Labels: 🍗 enhancement

#225 Fix problem that targetToken was lost when log in after log out
  navigation/Root.tsx
  redux/slices/auth.ts
Labels: 🔥 hotfix

#227 Fix schedule add, edit, delete permission check, Add user unblock
  components/ClubList.tsx
  components/Tag.tsx
  screens/Club/ClubApplication.tsx
  screens/Club/ClubFeedDetail.tsx
  screens/Club/ClubHome.tsx
  screens/Club/ClubNotification.tsx
  screens/Club/ClubScheduleModal.tsx
  screens/Club/ClubTopTabs.tsx
  screens/Home.tsx
  screens/Profile/BlockUserList.tsx
  screens/Profile/UserNotification.tsx
Labels: 🤖 android, 📱 iOS, 🎯 feature

#226 Modify only the selected image; Fix the clipping part of the club
  screens/Feed/ModifiyFeed.tsx
  screens/FeedCreation/ImageSelecter.tsx
  screens/FeedCreation/MyClubSelector.tsx
Labels: 🛠 bugfix, 🤖 android, 📱 iOS

#228 Add notifee module
  App.js
  android/build.gradle
  index.js
  navigation/Root.tsx
  package-lock.json
  package.json
  screens/Profile/UserNotification.tsx
  yarn.lock
Labels: 🤖 android, 📱 iOS, 🎯 feature

#229 23.03.09 로그인, 회원가입 디자인 검수
  App.js
  components/ClubList.tsx
  components/FeedDetail.tsx
  ios/Podfile.lock
  ios/onyoufrontend.xcodeproj/project.pbxproj
  navigation/SignupStack.tsx
  screens/ClubCreation/ClubCreationStepOne.tsx
  screens/ClubCreation/ClubCreationStepThree.tsx
  screens/ClubManagement/ClubEditIntroduction.tsx
  screens/Login/FindId.tsx
  screens/Login/FindIdResult.tsx
  screens/Login/FindLoginInfo.tsx
  screens/Login/FindPw.tsx
  screens/Login/FindPwResult.tsx
  screens/Login/Login.tsx
  screens/Profile/BlockUserList.tsx
  screens/Profile/Suggestion.tsx
  screens/SignUp/JoinConfirm.tsx
  screens/SignUp/JoinStepEight.tsx
  screens/SignUp/JoinStepFive.tsx
  screens/SignUp/JoinStepFour.tsx
  screens/SignUp/JoinStepNine.tsx
  screens/SignUp/JoinStepOne.tsx
  screens/SignUp/JoinStepSeven.tsx
  screens/SignUp/JoinStepSix.tsx
  screens/SignUp/JoinStepSuccess.tsx
  screens/SignUp/JoinStepThree.tsx
  screens/SignUp/JoinStepTwo.tsx
Labels: 🛠 bugfix, 🤖 android, 📱 iOS

#231 23.03.09 수정내역
  App.js
  navigation/ProfileStack.tsx
  screens/ClubCreation/ClubCreationStepTwo.tsx
  screens/Profile/Account.tsx
  screens/Profile/ChangePassword.tsx
  screens/Profile/ChangePw.tsx
  screens/SignUp/JoinStepFour.tsx
Labels: 🍗 enhancement, 🛠 bugfix, 🤖 android, 📱 iOS

#230 0309_More Fix
  screens/Feed/ModifiyFeed.tsx
  screens/FeedCreation/ImageSelecter.tsx
  screens/FeedCreation/MyClubSelector.tsx
Labels: 🛠 bugfix, 🤖 android

#233 Fix bottom button design to signup and club creation process
  api.ts
  components/BottomButton.tsx
  navigation/ClubStack.tsx
  screens/Club/ClubApplication.tsx
  screens/Club/ClubJoin.tsx
  screens/Club/ClubNotification.tsx
  screens/ClubCreation/ClubCreationFail.tsx
  screens/ClubCreation/ClubCreationStepOne.tsx
  screens/ClubCreation/ClubCreationStepThree.tsx
  screens/ClubCreation/ClubCreationStepTwo.tsx
  screens/ClubCreation/ClubCreationSuccess.tsx
  screens/Home.tsx
  screens/Profile/ChangePassword.tsx
  screens/Profile/UserNotification.tsx
  screens/SignUp/JoinConfirm.tsx
  screens/SignUp/JoinStepEight.tsx
  screens/SignUp/JoinStepFive.tsx
  screens/SignUp/JoinStepFour.tsx
  screens/SignUp/JoinStepOne.tsx
  screens/SignUp/JoinStepSeven.tsx
  screens/SignUp/JoinStepSix.tsx
  screens/SignUp/JoinStepSuccess.tsx
  screens/SignUp/JoinStepThree.tsx
  screens/SignUp/JoinStepTwo.tsx
Labels: 🛠 bugfix, 🤖 android, 📱 iOS

#235 Fix textinput layout
  components/ClubHeader.tsx
  components/ClubTabBar.tsx
  components/FeedDetail.tsx
  components/NotificationItem.tsx
  ios/onyoufrontend.xcodeproj/project.pbxproj
  screens/Club/ClubFeed.tsx
  screens/Club/ClubHome.tsx
  screens/Club/ClubJoin.tsx
  screens/Club/ClubNotification.tsx
  screens/Club/ClubScheduleAdd.tsx
  screens/Club/ClubScheduleEdit.tsx
  screens/Club/ClubScheduleModal.tsx
  screens/ClubCreation/ClubCreationStepOne.tsx
  screens/ClubCreation/ClubCreationStepThree.tsx
  screens/ClubCreation/ClubCreationStepTwo.tsx
  screens/ClubCreation/ClubCreationSuccess.tsx
  screens/ClubManagement/ClubEditBasics.tsx
  screens/ClubManagement/ClubEditIntroduction.tsx
  screens/ClubManagement/ClubManagementMain.tsx
  screens/Clubs.tsx
  screens/Feed/FeedComments.tsx
  screens/Feed/ModifiyFeed.tsx
  screens/Login/FindId.tsx
  screens/Login/FindIdResult.tsx
  screens/Login/FindPw.tsx
  screens/Login/FindPwResult.tsx
  screens/Profile.tsx
  screens/Profile/BlockUserList.tsx
  screens/Profile/ChangePassword.tsx
  screens/Profile/MyClub.tsx
  screens/Profile/Suggestion.tsx
  screens/Profile/UserNotification.tsx
Labels: 🛠 bugfix, 📱 iOS

#236 2023.03.12. Bug fix
  screens/Club/ClubJoin.tsx
  screens/Club/ClubTopTabs.tsx
  screens/ClubCreation/ClubCreationSuccess.tsx
  screens/ClubManagement/ClubManagementMain.tsx
  screens/Clubs.tsx
  screens/Feed/FeedComments.tsx
  screens/Login/FindId.tsx
  screens/Login/FindPw.tsx
  screens/Login/Login.tsx
  screens/Profile/EditProfile.tsx
  screens/SignUp/JoinStepSuccess.tsx
Labels: 🛠 bugfix, 🤖 android

#237 2023.03.13 BUG FIX
  api.ts
  components/ClubList.tsx
  navigation/Root.tsx
  navigation/Tabs.tsx
  screens/Club/ClubFeedDetail.tsx
  screens/Club/ClubHome.tsx
  screens/Club/ClubNotification.tsx
  screens/ClubCreation/ClubCreationStepThree.tsx
  screens/ClubManagement/ClubEditBasics.tsx
  screens/ClubManagement/ClubEditIntroduction.tsx
  screens/ClubManagement/ClubEditMembers.tsx
  screens/Clubs.tsx
  screens/Feed/FeedReportModal.tsx
  screens/Home.tsx
  screens/Login/Login.tsx
  screens/Profile/Account.tsx
  screens/Profile/BlockUserList.tsx
  screens/Profile/MyClub.tsx
  screens/Profile/Suggestion.tsx
Labels: 🍗 enhancement, 🛠 bugfix, 🤖 android, 📱 iOS

#238 Fix button position to club creation process
  components/BottomButton.tsx
  screens/ClubCreation/ClubCreationStepThree.tsx
  screens/ClubCreation/ClubCreationStepTwo.tsx
Labels: 🛠 bugfix, 🤖 android

#239 Fix button layout to club creation precess
  ios/onyoufrontend.xcodeproj/project.pbxproj
  screens/ClubCreation/ClubCreationStepThree.tsx
  screens/ClubCreation/ClubCreationStepTwo.tsx
Labels: 🛠 bugfix, 📱 iOS

#240 Fix scroll issue to sign up, Add aos back button routing to feed creation
  screens/ClubCreation/ClubCreationStepTwo.tsx
  screens/FeedCreation/ImageSelecter.tsx
  screens/SignUp/JoinStepFour.tsx
Labels: 🛠 bugfix, 🤖 android

#242 23.03.16 BUG FIX
  components/NotificationItem.tsx
  navigation/ClubStack.tsx
  screens/Club/ClubFeedDetail.tsx
  screens/Club/ClubNotification.tsx
  screens/Home.tsx
  screens/Profile/UserNotification.tsx
  screens/SignUp/JoinStepThree.tsx
Labels: 🛠 bugfix, 🤖 android, 📱 iOS

#241 ImageSelecter.tsx Design Fix
  screens/FeedCreation/ImageSelecter.tsx
Labels: 🍗 enhancement, 🤖 android, 📱 iOS

#243 Fix typo
  screens/FeedCreation/ImageSelecter.tsx
  screens/FeedCreation/MyClubSelector.tsx
Labels: 🔥 hotfix

#244 ImageSelecter.tsx Design Fix
  screens/FeedCreation/ImageSelecter.tsx
  screens/FeedCreation/MyClubSelector.tsx
Labels: 🛠 bugfix, 🤖 android

#245 Add read action to notification
  api.ts
  components/FeedDetail.tsx
  navigation/Root.tsx
  screens/Club/ClubNotification.tsx
  screens/ClubCreation/ClubCreationStepTwo.tsx
  screens/ClubManagement/ClubEditBasics.tsx
  screens/Profile/UserNotification.tsx
Labels: 🍗 enhancement, 🤖 android, 📱 iOS

#246 Refactor feed modification screen
  screens/Feed/ModifiyFeed.tsx
Labels: 🛠 bugfix, 🤖 android

#247 Fix scroll issue to feed modification screen
  ios/onyoufrontend.xcodeproj/project.pbxproj
  screens/Feed/ModifiyFeed.tsx
Labels: 🛠 bugfix, 📱 iOS

#248 23.03.16 BUG FIX
  navigation/Tabs.tsx
  screens/ClubCreation/ClubCreationStepTwo.tsx
  screens/ClubManagement/ClubEditBasics.tsx
  screens/Clubs.tsx
  screens/Feed/ModifiyFeed.tsx
  screens/Home.tsx
Labels: 🍗 enhancement, 🛠 bugfix, 🤖 android, 📱 iOS

#249 23.03.16 BUG FIX 3
  api.ts
  components/FeedDetail.tsx
  components/NotificationItem.tsx
  navigation/ClubStack.tsx
  navigation/Root.tsx
  screens/Club/ClubJoin.tsx
  screens/ClubCreation/ClubCreationStepThree.tsx
  screens/ClubCreation/ClubCreationStepTwo.tsx
  screens/ClubManagement/ClubEditBasics.tsx
  screens/ClubManagement/ClubEditIntroduction.tsx
  screens/Clubs.tsx
  screens/Feed/FeedComments.tsx
  screens/Feed/ModifiyFeed.tsx
  screens/FeedCreation/ImageSelecter.tsx
  screens/Home.tsx
  screens/Profile/EditProfile.tsx
  screens/Profile/NotificationSetting.tsx
  screens/Profile/UserNotification.tsx
Labels: 🍗 enhancement, 🛠 bugfix, 🤖 android, 📱 iOS

#251 Add club join reject message, firebase analytics and crashlytics.
  android/app/build.gradle
  android/build.gradle
  components/NotificationItem.tsx
  navigation/ClubStack.tsx
  navigation/Root.tsx
  navigation/SignupStack.tsx
  package-lock.json
  package.json
  screens/Club/ClubApplication.tsx
  screens/Club/ClubFeed.tsx
  screens/Club/ClubHome.tsx
  screens/Club/ClubJoin.tsx
  screens/Club/ClubJoinReject.tsx
  screens/Club/ClubJoinRejectMessage.tsx
  screens/Club/ClubNotification.tsx
  screens/Club/ClubScheduleAdd.tsx
  screens/Club/ClubScheduleEdit.tsx
  screens/Club/ClubScheduleModal.tsx
  screens/Club/ClubTopTabs.tsx
  screens/Clubs.tsx
  screens/Home.tsx
  screens/Profile/MyClub.tsx
  screens/Profile/UserNotification.tsx
  yarn.lock
Labels: 🤖 android, 🎯 feature

#252 Add firebase analytics and crashlytics to iOS
  ios/Podfile.lock
  ios/onyoufrontend.xcodeproj/project.pbxproj
  ios/onyoufrontend.xcodeproj/xcshareddata/xcschemes/onyoufrontend.xcscheme
  yarn.lock
Labels: 📱 iOS, 🎯 feature

#250 ImageSelecter Area Fix
  screens/FeedCreation/ImageSelecter.tsx
Labels: 🛠 bugfix

#253 Add firebase analytics setup to debugView
  ios/onyoufrontend.xcodeproj/xcshareddata/xcschemes/onyoufrontend.xcscheme
  ios/onyoufrontend/Info.plist
Labels: 📱 iOS, 🎯 feature

#254 23.03.18 UPDATE (v1.1.0)
  App.js
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/gradle.properties
  api.ts
  index.js
  navigation/ProfileStack.tsx
  navigation/Root.tsx
  package-lock.json
  package.json
  screens/ClubCreation/ClubCreationStepTwo.tsx
  screens/ClubManagement/ClubEditBasics.tsx
  screens/Clubs.tsx
  screens/Login/Login.tsx
  screens/Profile.tsx
  screens/Profile/Account.tsx
  screens/Profile/EditProfile.tsx
  screens/Profile/Info.tsx
  screens/Profile/MyClubs.tsx
  screens/Profile/NotificationSetting.tsx
  screens/Profile/Suggestion.tsx
  screens/Profile/UserNotification.tsx
  yarn.lock
Labels: 🤖 android, 🎯 feature

#256 Add club share feature
  App.js
  navigation/Root.tsx
  package-lock.json
  package.json
  screens/Club/ClubTopTabs.tsx
  yarn.lock
Labels: 🤖 android, 🎯 feature

#255 ImageSelecter TextArea Fix
  screens/FeedCreation/ImageSelecter.tsx
Labels: 🛠 bugfix

#257 Add firebase dynamic link to iOS
  ios/Podfile.lock
  ios/onyoufrontend.xcodeproj/project.pbxproj
  ios/onyoufrontend/Info.plist
  ios/onyoufrontend/onyoufrontend.entitlements
  screens/Club/ClubTopTabs.tsx
  screens/Login/Login.tsx
  screens/Profile.tsx
  yarn.lock
Labels: 📱 iOS, 🎯 feature

#258 ImageSelecter TextArea Fix
  screens/FeedCreation/ImageSelecter.tsx
Labels: 🛠 bugfix

#261 Update README.md
  README.md
Labels: 📖 documentation

#262 23.03.31 UPDATE
  android/app/build.gradle
  api.ts
  navigation/ClubCreationStack.tsx
  navigation/ClubManagementStack.tsx
  navigation/FeedStack.tsx
  navigation/Root.tsx
  navigation/SignupStack.tsx
  package-lock.json
  package.json
  screens/Club/ClubApplication.tsx
  screens/Club/ClubFeed.tsx
  screens/Club/ClubFeedDetail.tsx
  screens/Club/ClubJoinReject.tsx
  screens/Club/ClubScheduleAdd.tsx
  screens/Club/ClubScheduleEdit.tsx
  screens/Club/ClubTopTabs.tsx
  screens/ClubCreation/ClubCreationStepOne.tsx
  screens/ClubCreation/ClubCreationStepThree.tsx
  screens/ClubCreation/ClubCreationStepTwo.tsx
  screens/ClubManagement/ClubEditBasics.tsx
  screens/ClubManagement/ClubEditIntroduction.tsx
  screens/ClubManagement/ClubEditMembers.tsx
  screens/Clubs.tsx
  screens/Feed/FeedSelection.tsx
  screens/Feed/ModifiyFeed.tsx
  screens/FeedCreation/MyClubSelector.tsx
  screens/Home.tsx
  screens/Profile/NotificationSetting.tsx
  screens/SignUp/JoinConfirm.tsx
  screens/SignUp/JoinStepEight.tsx
  screens/SignUp/JoinStepFive.tsx
  screens/SignUp/JoinStepFour.tsx
  screens/SignUp/JoinStepSeven.tsx
  screens/SignUp/JoinStepSix.tsx
  screens/SignUp/JoinStepSuccess.tsx
  screens/SignUp/JoinStepThree.tsx
  screens/SignUp/JoinStepTwo.tsx
  types/User.ts
  types/feed.ts
  yarn.lock
Labels: 🍗 enhancement, 🛠 bugfix, 🤖 android
